GIFS = {
    #target GIFs
    "hug": [
        "https://media1.tenor.com/m/7f9CqFtd4SsAAAAd/hug.gif",
        "https://media1.tenor.com/m/wUQH5CF2DJ4AAAAd/horimiya-hug-anime.gif",
        "https://media1.tenor.com/m/nd_M3VFwVD0AAAAd/anime-hug.gif",
        "https://media1.tenor.com/m/HBTbcCNvLRIAAAAd/syno-i-love-you-syno.gif",
        "https://media1.tenor.com/m/W9Z5NRFZq_UAAAAd/excited-hug.gif",
        "https://media1.tenor.com/m/G_IvONY8EFgAAAAd/aharen-san-anime-hug.gif",
        "https://media1.tenor.com/m/wUV305b21qoAAAAd/paar-umarmung.gif",
        "https://media1.tenor.com/m/m_bbfF_KS-UAAAAd/engage-kiss-anime-hug.gif",
        "https://media1.tenor.com/m/PuuhAT9tMBYAAAAd/anime-cuddles.gif",
        "https://media1.tenor.com/m/J7eGDvGeP9IAAAAd/enage-kiss-anime-hug.gif",
        "https://media1.tenor.com/m/NgriQrF0JbkAAAAd/anime-cuddle.gif",
        "https://media1.tenor.com/m/0KYDZQ3Qjg8AAAAd/girl-side.gif",
        "https://media1.tenor.com/m/hYe-gAUD-TwAAAAd/kitsuneupload-anime.gif",
        "https://media1.tenor.com/m/KcY2lEdxFlwAAAAd/kitsune-upload-news.gif",
        "https://media1.tenor.com/m/HOUIecxb-5YAAAAd/kitsune-upload-anime.gif",
        "https://media1.tenor.com/m/arMxz72tc50AAAAC/catgirl-hug.gif",
        "https://media1.tenor.com/m/FgLRE4gi5VoAAAAd/hugs-cute.gif",
        "https://media1.tenor.com/m/PMJdOBkmPUMAAAAC/hug-anime-kurome.gif",
        "https://media1.tenor.com/m/BFmsQg9J1ZMAAAAC/chikako-hugging-otohime-for-the-first-and-she-confused.gif",
        "https://media1.tenor.com/m/VQURjAnQwRkAAAAd/hug.gif",
        "https://media1.tenor.com/m/LlGpbY_LqigAAAAd/anime-anime-girls.gif",
        "https://media1.tenor.com/m/r1Lxsua8zBIAAAAd/hug.gif",
        "https://media1.tenor.com/m/Fu4c5Ym3pS8AAAAd/himeno-himeno-csm.gif",
        "https://media1.tenor.com/m/mZdHYO8urvUAAAAd/natsu-natsu-dragneel.gif",
        "https://media1.tenor.com/m/kJO1g6LDZSoAAAAd/tanjiro-demon-slayer.gif",
        "https://media1.tenor.com/m/AO-1yttBeH8AAAAd/anime-hug.gif",
        "https://media1.tenor.com/m/jfi-A6XmGZAAAAAd/hug-spin.gif",
        "https://media1.tenor.com/m/d0AdL1hRqcIAAAAd/high-school-dxd-rias.gif",
        "https://media1.tenor.com/m/q9Mk711vGI0AAAAC/hug.gif",
        "https://media1.tenor.com/m/MA5H68SBHcAAAAAd/hug-anime.gif",
        "https://media1.tenor.com/m/VLaywF3qc7gAAAAd/naruto-shippuden-anime.gif",
        "https://media1.tenor.com/m/oIVFJdaUcqYAAAAd/one-piece-chopper.gif",
        "https://media1.tenor.com/m/G3jM2zSBbXsAAAAd/oden-and-toki-one-piece.gif",
        "https://media1.tenor.com/m/bSf01Gv-5HIAAAAd/hug.gif",
        "https://media1.tenor.com/m/nUsuAnQw_7QAAAAC/nel-bleach.gif",
        "https://media1.tenor.com/m/2FNnJH3oPxgAAAAd/hug.gif",
        "https://media1.tenor.com/m/WgvpDBxRCewAAAAd/naruto-himawari.gif",
        "https://media1.tenor.com/m/D4HrmF302vYAAAAC/naruto-anime.gif",
        "https://media1.tenor.com/m/nJJtEppateMAAAAd/anime-couple.gif",
        "https://media1.tenor.com/m/WcdyzmdyZyYAAAAC/anime-hug.gif",
        "https://media1.tenor.com/m/2SoeEKnOiaAAAAAC/kurosaki-ichigo-tybw.gif",
        "https://media1.tenor.com/m/RTk8RVZCjggAAAAd/giselle-gewelle-giselle.gif",
        "https://media1.tenor.com/m/vBzOvBQ5MugAAAAC/citrus-harumi.gif",
        "https://media1.tenor.com/m/agsH6ho00ZoAAAAC/anime-huggle.gif"
    ],
    "uppercut": [
        "https://media1.tenor.com/m/blYwpMNaaCUAAAAC/nichijou-uppercut.gif",
        "https://media1.tenor.com/m/EOIhFxcnau4AAAAC/jujutsu-kaisen-yuji-itadori.gif",
        "https://media1.tenor.com/m/0DqAGBxWL5UAAAAC/kamijo-index.gif",
        "https://media1.tenor.com/m/CxwPJZ9wgggAAAAC/anime-uppercut.gif",
        "https://media1.tenor.com/m/4z26A7YW15EAAAAC/strong-heavy-punch.gif",
        "https://media1.tenor.com/m/E0TH2kuD90sAAAAC/android17-uppercut.gif",
        "https://media1.tenor.com/m/h_9eMTs9TXoAAAAC/hajime-no-ippo-sendo.gif",
        "https://media1.tenor.com/m/kFL3iEag_60AAAAC/azumanga-daioh-azumanga.gif",
        "https://media1.tenor.com/m/jRardsEzmvoAAAAC/black-star-soul-eater-not.gif",
        "https://media1.tenor.com/m/2jPQAtVkd2EAAAAC/neji-naruto.gif",
        "https://media1.tenor.com/m/lbWaXRbmHzYAAAAC/sasuke-vs-naruto-fight.gif",
        "https://media1.tenor.com/m/yJWRCs5JzlUAAAAC/franky-punch-uppercut-franky.gif"
    ],
    "dropkick": [
        "https://media1.tenor.com/m/w3_5V8KfRO4AAAAC/kick-anime.gif",
        "https://media1.tenor.com/m/Ay1Nm0X2VP8AAAAC/falling-from-window-anime-death.gif",
        "https://media1.tenor.com/m/J3Lc1VDcZ4UAAAAC/dbz-dragon-ball-z.gif",
        "https://media1.tenor.com/m/2wmVyLuDzVAAAAAC/bnc.gif",
        "https://media1.tenor.com/m/LnHTJttnYIkAAAAC/ayaka-drop-kick.gif",
        "https://media1.tenor.com/m/mEgexCY-65QAAAAC/toradora-taiga.gif",
        "https://media1.tenor.com/m/KJsgTGUSCH4AAAAC/space-dandy-anime.gif",
        "https://media1.tenor.com/m/rWtrmtjzyZQAAAAC/kick.gif"
    ],
    "punch": [
        "https://media1.tenor.com/m/yA_KtmPI1EMAAAAC/hxh-hunter-x-hunter.gif",
        "https://media1.tenor.com/m/p_mMicg1pgUAAAAC/anya-forger-damian-spy-x-family.gif",
        "https://media1.tenor.com/m/SwMgGqBirvcAAAAC/saki-saki-kanojo-mo-kanojo.gif",
        "https://media1.tenor.com/m/BoYBoopIkBcAAAAC/anime-smash.gif",
        "https://media1.tenor.com/m/hu9e3k1zr0IAAAAC/pjsk-pjsk-anime.gif",
        "https://media1.tenor.com/m/jVeoj7B-OxEAAAAC/punch-anime.gif",
        "https://media1.tenor.com/m/pNmajM4wmtkAAAAC/punch-smash.gif",
        "https://media1.tenor.com/m/i3hP7zju5JYAAAAC/higurashi-sotsu.gif",
        "https://media1.tenor.com/m/6a42QlkVsCEAAAAC/anime-punch.gif",
        "https://media1.tenor.com/m/UK-nHsdngT0AAAAC/sakura-punch-naruto.gif",
        "https://media1.tenor.com/m/sn74zq5iZSQAAAAC/one-piece-is-real-vivi.gif",
        "https://media1.tenor.com/m/9hBwXT9okiAAAAAC/one-piece-anime.gif"
    ],
    "highfive": [
        "https://media1.tenor.com/m/WYlL-2Mu_78AAAAC/blue-lock-anime.gif",
        "https://media1.tenor.com/m/TP6qnyGR3ycAAAAC/bluelock-isagi.gif",
        "https://media1.tenor.com/m/JBBZ9mQntx8AAAAd/anime-high-five.gif",
        "https://media1.tenor.com/m/ia0eAUSTgHAAAAAd/high-five-high5.gif",
        "https://media1.tenor.com/m/ENGhNOukmSoAAAAC/vermeil-in-gold-alto-goldfield.gif",
        "https://media1.tenor.com/m/TTQUkHkSAisAAAAC/high-touch-satoshi.gif",
        "https://media1.tenor.com/m/geq2owR6VPMAAAAC/ban-meliodas.gif",
        "https://media1.tenor.com/m/YCub_pFV2uAAAAAC/anime-high.gif",
        "https://media1.tenor.com/m/VaOkUsy8UjMAAAAC/hi-five-high-five.gif",
        "https://media1.tenor.com/m/AlFl2dckMe4AAAAC/fresh-precure-high-five.gif",
        "https://media1.tenor.com/m/zuGJiqsnkPIAAAAC/eevee-pikachu.gif",
        "https://media1.tenor.com/m/Ajl4l3PWf8sAAAAC/high-five-anime.gif",
        "https://media1.tenor.com/m/uJ4U79P2uFEAAAAC/hunter-x-hunter-high-five.gif",
        "https://media1.tenor.com/m/U_Gxnaz7BTgAAAAC/anime-high-five.gif",
        "https://media1.tenor.com/m/rU9PEKyn4BsAAAAC/fairy-tail-nalu.gif",
        "https://media1.tenor.com/m/yCNsaEbq9dgAAAAC/kirito-anime.gif",
        "https://media1.tenor.com/m/vYG722Cn4H0AAAAC/aoi-todo-yuji-itadori.gif"
    ],
    "fistbump": [
        "https://media1.tenor.com/m/CMvCx0a_RZsAAAAC/friends-fist-bump.gif",
        "https://media1.tenor.com/m/siuUf3q5_9AAAAAC/gundam-ibo-iron-blooded-orphans.gif",
        "https://media1.tenor.com/m/sU3cGUn-cZQAAAAC/little-witch-academia-atsuko-kagari.gif",
        "https://media1.tenor.com/m/AC6OR-VHlIoAAAAC/soul-eater-bromance.gif",
        "https://media1.tenor.com/m/8gFzflXpECIAAAAd/kurama-naruto.gif",
        "https://media1.tenor.com/m/tEatklmWDKMAAAAd/fairy-tail-anime.gif",
        "https://media1.tenor.com/m/5HfJFlimdRMAAAAd/fist-bump-anime-dbz.gif",
        "https://media1.tenor.com/m/SWexdoGm5-wAAAAC/mushoku-tensei-jobless-reincarnation.gif",
        "https://media1.tenor.com/m/ZyH0Jks08loAAAAd/naruto-sasuke-fistbumb.gif",
        "https://media1.tenor.com/m/pBjSyy6ItmgAAAAC/fist-bump-anime.gif",
        "https://media1.tenor.com/m/xrtt05uSCw0AAAAC/bump-fist.gif",
        "https://media1.tenor.com/m/-gG1h853X_EAAAAC/shiki-granbell-pino.gif",
        "https://media1.tenor.com/m/yB9V_6y0LaUAAAAC/fist-bump-with-bff.gif",
        "https://media1.tenor.com/m/SwsORGd-boMAAAAd/blue-lock-oh-yeah-yeah.gif",
        "https://media1.tenor.com/m/ifwFy7jvDgwAAAAC/anime-brofist-anime-bro-fist.gif"
    ],
    "slap": [
        "https://media1.tenor.com/m/Sv8LQZAoQmgAAAAd/chainsaw-man-csm.gif",
        "https://media1.tenor.com/m/Ws6Dm1ZW_vMAAAAd/girl-slap.gif",
        "https://media1.tenor.com/m/8bSm0lI4_FUAAAAd/yuuri.gif",
        "https://media1.tenor.com/m/jHHh-w7-cxgAAAAC/jujutsu-kaisen-todo-aoi.gif",
        "https://media1.tenor.com/m/WYmal-WAnksAAAAC/yuzuki-mizusaka-nonoka-komiya.gif",
        "https://media1.tenor.com/m/MXZGFeabIIwAAAAC/taiga-toradora.gif",
        "https://media1.tenor.com/m/5jBuDXkDsjYAAAAC/slap.gif",
        "https://media1.tenor.com/m/7xFcP1KWjY0AAAAC/no.gif",
        "https://media1.tenor.com/m/wTzNeEgfPicAAAAC/anime-punch.gif",
        "https://media1.tenor.com/m/rVXByOZKidMAAAAC/anime-slap.gif",
        "https://media1.tenor.com/m/1-1M4PZpYcMAAAAC/tsuki-tsuki-ga.gif",
        "https://media1.tenor.com/m/zdHAYZowRSMAAAAC/chiyuki-fujito-slap.gif",
        "https://media1.tenor.com/m/HTHoXnBc400AAAAC/in-your-face-slap.gif",
        "https://media1.tenor.com/m/00huTPPw5HIAAAAC/nami-sanji.gif",
        "https://media1.tenor.com/m/NKuG255mKOcAAAAC/nami-zoro.gif",
        "https://media1.tenor.com/m/VlSXTbFcvDQAAAAC/naruto-anime.gif",
        "https://media1.tenor.com/m/ZFsMkVPpsfUAAAAC/gintama-sadaharu.gif"
    ],
    "handshake": [
        "https://media1.tenor.com/m/rmklzHMYy80AAAAC/nichijou-anime.gif",
        "https://media1.tenor.com/m/YhsYMfR-zdsAAAAC/fma-fullmetal-alchemist.gif",
        "https://media1.tenor.com/m/NUK_dpuFZ9gAAAAC/inazuma-eleven-ina11.gif"
    ],
    "wave": [
        "https://media1.tenor.com/m/xsICn9T81LcAAAAC/roy-leops.gif",
        "https://media1.tenor.com/m/1MfQk9vFF7MAAAAC/anime-bye-bye-maki.gif",
        "https://media1.tenor.com/m/AuBOgaPV41cAAAAC/shinya-shinyahiragi.gif",
        "https://media1.tenor.com/m/k0D7Goir718AAAAC/holo-spice-and-wolf.gif",
        "https://media1.tenor.com/m/DBcVKLog4qUAAAAC/sasaki-to-miyano-sasaki-and-miyano.gif",
        "https://media1.tenor.com/m/H4xLf6epW-wAAAAC/anime-wave.gif",
        "https://media1.tenor.com/m/vsQmbET1T84AAAAC/spyxfamily-spy-x-family.gif"
    ],
    "stab": [
        "https://media1.tenor.com/m/b7UhYIWfmXEAAAAC/yumeko-mirai-nikki.gif",
        "https://media1.tenor.com/m/E2fkDPkSyIMAAAAC/yu-vs-mika-seraph-of-the-end.gif",
        "https://media1.tenor.com/m/CWsbJDl70tsAAAAC/shimoneta.gif",
        "https://media1.tenor.com/m/Z_2nHtfScl0AAAAC/higurashi-when-they-cry.gif"
    ],
    "flirt": [
        "https://media1.tenor.com/m/boVQzqMZwBIAAAAC/anime-pat-anime-girl.gif",
        "https://media1.tenor.com/m/c1oQ1icY4zMAAAAC/hot.gif",
        "https://media1.tenor.com/m/LcEZK9jNp2MAAAAC/ijiranaide-nagatoro-san-hayase-nagatoro.gif",
        "https://media1.tenor.com/m/q2WgdrY4SL0AAAAd/darling.gif"
    ],
    "throw": [
        "https://media1.tenor.com/m/FSnIhyulqvcAAAAC/hit-thrown.gif",
        "https://media1.tenor.com/m/N42xzcb3Lg4AAAAC/yato-angry.gif",
        "https://media1.tenor.com/m/tmt1kX9T5_MAAAAC/anime.gif",
        "https://media1.tenor.com/m/EfhPfbG0hnMAAAAC/slap-handa-seishuu.gif",
        "https://media1.tenor.com/m/02ofINPVZxoAAAAC/throw-book-fall.gif",
        "https://media1.tenor.com/m/Gqt_vhCUwh0AAAAC/the-demon-prince-of-momochi-shoe.gif"
    ],
    "lick": [
        "https://media1.tenor.com/m/zIU_JbsnMQ8AAAAC/zatch-bell-golden-gash.gif",
        "https://media1.tenor.com/m/Pb1JPfqXpAIAAAAC/lick-licky.gif",
        "https://media1.tenor.com/m/S5I9g4dPRn4AAAAC/omamori-himari-manga.gif",
        "https://media1.tenor.com/m/KQZIn3BzpkcAAAAC/kirari-kirari-momobami.gif"
    ],
    "feed": [
        "https://media1.tenor.com/m/Aflxvrwa0woAAAAC/kawaii-wholesome.gif",
        "https://media1.tenor.com/m/y_xVq9Ea-YUAAAAC/anime-acchi-kocchi.gif",
        "https://media1.tenor.com/m/LnyFkFCz0ucAAAAC/reina-aharen-meatball.gif",
        "https://media1.tenor.com/m/qi8MqDKmpl8AAAAC/lycoris-recoil-chisato.gif",
        "https://media1.tenor.com/m/xS09IqCS1e0AAAAC/anime-anime-boy.gif",
        "https://media1.tenor.com/m/_Wn5KdSnphEAAAAC/anime-feed-anime.gif",
        "https://media1.tenor.com/m/gIbE9pZ7raYAAAAC/wataten-watashi-ni-tenshi-ga-maiorita.gif"
    ],
    "headpat": [
        "https://media1.tenor.com/m/edHuxNBD6IMAAAAC/anime-head-pat.gif",
        "https://media1.tenor.com/m/3PjRNS8paykAAAAC/pat-pat-head.gif",
        "https://media1.tenor.com/m/OvrmH29V-44AAAAC/pat.gif",
        "https://media1.tenor.com/m/oUS1jdJBkIwAAAAC/sakuta-azusagawa-mai-sakurajima.gif",
        "https://media1.tenor.com/m/wLqFGYigJuIAAAAC/mai-sakurajima.gif",
        "https://media1.tenor.com/m/7xrOS-GaGAIAAAAC/anime-pat-anime.gif",
        "https://media1.tenor.com/m/Wrr4rxTqrrkAAAAC/futeki-fearless.gif",
        "https://media1.tenor.com/m/-hkJYNs7tUkAAAAC/anime-pat.gif",
        "https://media1.tenor.com/m/MDc4TSck5PQAAAAC/frieren-anime.gif",
        "https://media1.tenor.com/m/sxoZANeqrT0AAAAC/headpats-anime.gif",
        "https://media1.tenor.com/m/RWAVN9L5yzYAAAAC/loli-lolita.gif",
        "https://media1.tenor.com/m/OGnRVWCps7IAAAAC/anime-head-pat.gif",
        "https://media1.tenor.com/m/bWcd47RCIo0AAAAC/pat.gif",
        "https://media1.tenor.com/m/2iQbqC7NsJsAAAAC/lawine-frieren.gif",
        "https://media1.tenor.com/m/4PIWT36zHo0AAAAC/anime-pat.gif",
        "https://media1.tenor.com/m/uNT-3nchwysAAAAC/headpats-anime.gif"
    ],
    "suplex": [
        "https://media1.tenor.com/m/vrYB1o2OY1IAAAAC/gintama-gintoki.gif",
        "https://media1.tenor.com/m/N4CSeJCk1HsAAAAC/kureha-sakamachi.gif",
        "https://media1.tenor.com/m/rwgdnhaZ8UUAAAAC/power-anime.gif",
        "https://media1.tenor.com/m/b3qy6Po4-2cAAAAC/hataage-suplex-princess.gif",
        "https://media1.tenor.com/m/gkYwdy1NWcUAAAAC/nichijou-anime.gif",
        "https://media1.tenor.com/m/DJOClHUo_aUAAAAC/jujutsu-kaisen-megumi-fushiguro.gif",
        "https://media1.tenor.com/m/pRW5ZWeLeCEAAAAC/suplex-throw.gif",
        "https://media1.tenor.com/m/MPMfjKHxnuYAAAAC/anime.gif",
        "https://media1.tenor.com/m/gfJsYF6IP2UAAAAC/anime-fight-suplex.gif",
        "https://media1.tenor.com/m/jDjvFwEX40QAAAAC/the-god-of-highschool-goh.gif"
    ],
    "yeet": [
        "https://media1.tenor.com/m/VaRDRo2dqSAAAAAd/vnc-vanitas.gif",
        "https://media1.tenor.com/m/LTtlQgsvSsUAAAAC/yeet-toradora.gif",
        "https://media1.tenor.com/m/tc2d7QTcUokAAAAC/the-strongest-sage-with-the-weakest-crest-iris.gif",
        "https://media1.tenor.com/m/AVkcj1Ex1qIAAAAC/yeet-anime.gif",
        "https://media1.tenor.com/m/D34kJelwaWsAAAAC/yeet-anime.gif",
        "https://media1.tenor.com/m/XVIHXa7Jv5IAAAAC/haikyuu-kageyama-tobio.gif",
        "https://media1.tenor.com/m/MSJazsGdIcAAAAAC/out-fly.gif",
        "https://media1.tenor.com/m/eINJkTkMB-kAAAAC/smash-anime.gif",
        "https://media1.tenor.com/m/qCTnY5ry2gEAAAAC/anime-throw.gif"
    ],
    "bite": [
        "https://media1.tenor.com/m/5mVQ3ffWUTgAAAAC/anime-bite.gif",
        "https://media1.tenor.com/m/L8GrZ1X6ThsAAAAC/bite.gif",
        "https://media1.tenor.com/m/_AkeqheWU-4AAAAC/anime-bite.gif",
        "https://media1.tenor.com/m/ifbb8c3S4u8AAAAC/anime-bite.gif",
        "https://media1.tenor.com/m/0neaBmDilHsAAAAC/anime-bite.gif",
        "https://media1.tenor.com/m/ECCpi63jZlUAAAAC/anime-bite.gif",
        "https://media1.tenor.com/m/48DDFOcNQBYAAAAC/anime-bite.gif",
        "https://media1.tenor.com/m/n__KGrZPlQEAAAAC/bite.gif"
    ],
    "poke": [
        "https://media1.tenor.com/m/iu_Lnd86GxAAAAAC/nekone-utawarerumono.gif",
        "https://media1.tenor.com/m/3dOqO4vVlr8AAAAC/poke-anime.gif",
        "https://media1.tenor.com/m/5j7eivfftw8AAAAC/poke.gif",
        "https://media1.tenor.com/m/7iV_gBGrRAUAAAAC/boop-poke.gif",
        "https://media1.tenor.com/m/vu1AUXE8wtsAAAAC/anime-sleep.gif",
        "https://media1.tenor.com/m/y4R6rexNEJIAAAAC/boop-anime.gif",
        "https://media1.tenor.com/m/vVtDnV6IEGYAAAAC/my-deer.gif",
        "https://media1.tenor.com/m/HJa3EjH0iNMAAAAC/poke.gif",
        "https://media1.tenor.com/m/gMqsQ1wwbhgAAAAC/anime-poke.gif",
        "https://media1.tenor.com/m/aFn-VfDXmSYAAAAC/poke-trick.gif"
    ],
    "boop": [
        "https://media1.tenor.com/m/gCjGIzaz-BMAAAAC/rwby-nora.gif",
        "https://media1.tenor.com/m/4OHxyGd4qp0AAAAC/boop-nose.gif",
        "https://media1.tenor.com/m/OFnBNTdwXwQAAAAC/boop.gif",
        "https://media1.tenor.com/m/G5u3bfszOPMAAAAC/anime-picking-nose.gif",
        "https://media1.tenor.com/m/hAIMw-_f6hYAAAAC/anime-girl.gif"
    ],
    "spank": [
        "https://media1.tenor.com/m/p_0w4-41-E0AAAAC/kimetsu-no.gif",
        "https://media1.tenor.com/m/Ep5dFoM0h5gAAAAC/bad-spank.gif",
        "https://media1.tenor.com/m/B5oC9lACJ9kAAAAC/anime-spank.gif",
        "https://media1.tenor.com/m/qhdaIdgiV78AAAAC/anime-spank.gif",
        "https://media1.tenor.com/m/Sp7yE5UzqFMAAAAC/spank-slap.gif",
        "https://media1.tenor.com/m/uER90n0laEEAAAAC/anime-spanking.gif",
        "https://media1.tenor.com/m/iz6t2EwKeYMAAAAC/rikka-takanashi-chunibyo.gif"
    ],
    "cuddle": [
        "https://media1.tenor.com/m/SAL_XAuyuJAAAAAC/cute-anime.gif",
        "https://media1.tenor.com/m/bLttPccI_I4AAAAC/cuddle-anime.gif",
        "https://media1.tenor.com/m/fxTZ2zrDasAAAAAC/bed-hug-cuddles.gif",
        "https://media1.tenor.com/m/MApGHq5Kvj0AAAAC/anime-hug.gif",
        "https://media1.tenor.com/m/GCWKqT1ukt4AAAAC/hold-me-couple.gif",
        "https://media1.tenor.com/m/MnFw3d0TjK4AAAAC/anime-hug.gif",
        "https://media1.tenor.com/m/x2785kFjcDkAAAAC/hug-anime.gif",
        "https://media1.tenor.com/m/We9ZtQtm8EwAAAAC/cuddle-cuddles.gif",
        "https://media1.tenor.com/m/Q-seMbfISyAAAAAC/cuddle.gif"
    ],
    "glomp": [
        "https://media1.tenor.com/m/7CeI4Tsmz7QAAAAC/anime-tackle.gif",
        "https://media1.tenor.com/m/9VAhRQHql5MAAAAC/anime-hug.gif",
        "https://media1.tenor.com/m/eoZ25OAvxkIAAAAC/chobits-hideki-motosuwa.gif",
        "https://media1.tenor.com/m/kWzhQRpqK8kAAAAC/shikimori-anime-hug.gif",
        "https://media1.tenor.com/m/emtBa056cGsAAAAC/anime-girl.gif",
        "https://media1.tenor.com/m/WQCzwCMxXocAAAAC/happy-yay.gif",
        "https://media1.tenor.com/m/76y238MOOnkAAAAC/anime.gif"
    ],
    "flyingkiss": [
        "https://media1.tenor.com/m/xDCr6DNYcZEAAAAC/sealyx-frieren-beyond-journey%27s-end.gif",
        "https://media1.tenor.com/m/I6SNhJs-HuUAAAAC/kiss-hot.gif",
        "https://media1.tenor.com/m/vberBgo__S4AAAAC/naruko-anime.gif",
        "https://media1.tenor.com/m/MtKkjQF4rz4AAAAC/kiss-anime.gif",
        "https://media1.tenor.com/m/7s-3eQ3MNtsAAAAC/laughs-kiis.gif",
        "https://media1.tenor.com/m/7-ZkKJ22bcgAAAAC/blow-kiss-anime.gif",
        "https://media1.tenor.com/m/4cmP_Dfn4WMAAAAC/uwu-cute.gif",
        "https://media1.tenor.com/m/43qt_qk-LWkAAAAC/cute-anime.gif",
        "https://media1.tenor.com/m/M--gmEkMIp4AAAAC/rock-lee-sakura-haruno.gif",
        "https://media1.tenor.com/m/34YWvoJql20AAAAC/one-piece-one-piece-3d2y.gif"
    ],
    "foreheadkiss": [
        "https://media1.tenor.com/m/ivnnNqJ5_HwAAAAC/kiss-sweet.gif",
        "https://media1.tenor.com/m/9rN8nw7pVcEAAAAC/anime-kiss.gif",
        "https://media1.tenor.com/m/t4U2xjlAfeIAAAAC/forehead-anime.gif",
        "https://media1.tenor.com/m/q9bruJEDCBQAAAAC/forehead-kiss-sweet.gif",
        "https://media1.tenor.com/m/sqEQsPKYWvcAAAAC/terry-kiss-claudia-terry-kiss-forehead.gif"
    ],
    "pullcheek": [
        "https://media1.tenor.com/m/ISN_bpY007QAAAAC/cute-pinch-cheek.gif",
        "https://media1.tenor.com/m/tzyT14OUww4AAAAC/majo-no-tabitabi-elaina.gif",
        "https://media1.tenor.com/m/WNYq1bAEdAcAAAAC/anime-cheeks.gif",
        "https://media1.tenor.com/m/2rwxALHum7wAAAAC/pulls-cheek-youre-so-cute.gif",
        "https://media1.tenor.com/m/eirioESfPi4AAAAd/maria-kujou-masachika-kuze.gif",
        "https://media1.tenor.com/m/LRgPF3ycRl0AAAAC/anime-angry.gif",
        "https://media1.tenor.com/m/aApaaPTuEvYAAAAC/anime-hibike-euphonium.gif",
        "https://media1.tenor.com/m/uVWSMuLakUwAAAAC/idolish7-trigger.gif",
        "https://media1.tenor.com/m/uc-VyaLh04UAAAAC/sakuta-azusagawa-bunny-girl.gif",
        "https://media1.tenor.com/m/_nnMGibAy3kAAAAC/margarete-wien-shibuya-kanon.gif"
    ],
    "shoot": [
        "https://media1.tenor.com/m/o3BdaQJjVqsAAAAC/black-lagoon-revy.gif",
        "https://media1.tenor.com/m/Qbwl5IkdfqgAAAAC/bang-black-lagoon.gif",
        "https://media1.tenor.com/m/AGTqt-wXyiEAAAAC/nichijou-minigun.gif",
        "https://media1.tenor.com/m/gQkJLMcaZiIAAAAC/anime-gun.gif",
        "https://media1.tenor.com/m/guXgm-Ie55wAAAAC/anime-gun.gif",
        "https://media1.tenor.com/m/Pq3EQbsynG8AAAAC/fire-power.gif",
        "https://media1.tenor.com/m/CHIZ_4VEYoIAAAAC/succfishy-burst-angel.gif",
        "https://media1.tenor.com/m/Vja2MkojIgsAAAAC/anime-gun.gif"
    ],
    "cheer": [
        "https://media1.tenor.com/m/d2NYSXokaK4AAAAC/pikachu-cheer-dance.gif",
        "https://media1.tenor.com/m/fKjC8KynhWYAAAAC/anime-anime-cheerleader.gif",
        "https://media1.tenor.com/m/ka7tt4QuxQgAAAAC/oshi-no-ko-cheers.gif",
        "https://media1.tenor.com/m/iFUyEZSmMTsAAAAC/hanamaru-kindergarten-anime.gif",
        "https://media1.tenor.com/m/orzkxmYJCqwAAAAC/cure-yell-kira-kira-precure-a-la-mode.gif",
        "https://media1.tenor.com/m/ur4ieA_PZp0AAAAC/diosa-bocchi.gif",
        "https://media1.tenor.com/m/hV03QzfXrtEAAAAC/hatsune-priconne.gif"
    ],
    #solo GIFs
    "sad": [
        "https://media1.tenor.com/m/7ENDCWgOVm0AAAAC/anime-bocchi-the-rock.gif",
        "https://media1.tenor.com/m/aGo0xPeeZwgAAAAC/anime-kanna.gif",
        "https://media1.tenor.com/m/6EQ2aeffrU0AAAAC/anime-sad.gif",
        "https://media1.tenor.com/m/eCzS77GgsR8AAAAC/bath-anime-girl.gif",
        "https://media1.tenor.com/m/EudvjJemPC0AAAAC/bocchi-the.gif",
        "https://media1.tenor.com/m/rBNFP6lkSfAAAAAC/sad.gif",
        "https://media1.tenor.com/m/rIxSGq0uvF4AAAAC/anime-satania.gif",
        "https://media1.tenor.com/m/777c5_jRXLQAAAAC/dead-inside.gif"
    ],
    "die": [
        "https://media1.tenor.com/m/GyFbT8ZoyqAAAAAC/kanokari-anime-fall.gif",
        "https://media1.tenor.com/m/qEBvxi73QRYAAAAC/anime-bocchi.gif",
        "https://media1.tenor.com/m/0Uf0-C5vSHMAAAAC/died-of-cringe-anime.gif",
        "https://media1.tenor.com/m/9Ql_VyYvMZkAAAAC/anime-sleeping.gif",
        "https://media1.tenor.com/m/_aMkVJcxClIAAAAC/yu-yu-hakusho-anime.gif",
        "https://media1.tenor.com/m/fT_gwZ3_Y7EAAAAC/tired-dead.gif"
    ],
    "solodance": [
        "https://media1.tenor.com/m/9eu9F42NQuYAAAAC/dance-anime-cool.gif",
        "https://media1.tenor.com/m/mFEGA0NoEakAAAAC/fortnite-dance-anime.gif",
        "https://media1.tenor.com/m/wFtRdoHX-ssAAAAC/dance-happy.gif",
        "https://media1.tenor.com/m/jySJroymS38AAAAC/ruby-hoshino-oshi-no-ko.gif",
        "https://media1.tenor.com/m/7L4T7SACcF8AAAAC/tanzen.gif",
        "https://media1.tenor.com/m/M7-Ftr7tsz8AAAAC/dance.gif",
        "https://media1.tenor.com/m/GOYRQva4UeoAAAAC/anime-dance.gif"
    ],
    "smirk": [
        "https://media1.tenor.com/m/vqn1xQaUgpwAAAAC/keara-chan-girl-keyaru.gif",
        "https://media1.tenor.com/m/Qr778oyy2VgAAAAC/jashin-chan-dropkick-on-my-devil.gif",
        "https://media1.tenor.com/m/kyI_yjIwKE8AAAAd/anime-smirk-anime-perverted-smirk.gif",
        "https://media1.tenor.com/m/gPPUbLL-tgwAAAAC/yamada-kun-to-lv999-no-koi-wo-suru-my-love-story-with-yamada-kun-at-lv999.gif",
        "https://media1.tenor.com/m/E7qBgAqGTWsAAAAC/smug-anime.gif"
    ],
    "cry": [
        "https://media1.tenor.com/m/xllv31ZfmZIAAAAC/nagisa-hazuki-anime.gif",
        "https://media1.tenor.com/m/gK-GwW8KEmEAAAAC/asteroid-in-love-anime.gif",
        "https://media1.tenor.com/m/35S_M89zT3sAAAAC/horimiya-anime.gif",
        "https://media1.tenor.com/m/WOIleOQXKoEAAAAC/cry.gif",
        "https://media1.tenor.com/m/0qj0aqZ0nucAAAAC/anya-spy-x-family-anime-anya-crying.gif" 
    ],
    "laugh": [
        "https://media1.tenor.com/m/mzIscFHY8L0AAAAC/blue-box-ao-no-hako.gif",
        "https://media1.tenor.com/m/RQayAFoMNJEAAAAC/gojo-satoru.gif",
        "https://media1.tenor.com/m/9fkrMIGeSaIAAAAC/hakase-shinonome-nichijou.gif",
        "https://media1.tenor.com/m/m3eR2kqrb1oAAAAC/laugh.gif",
        "https://media1.tenor.com/m/0CmFMbcGVKUAAAAC/spy-x-family-anime.gif",
        "https://media1.tenor.com/m/rwmF-6Q5xesAAAAC/momo-ayase-ayase-momo.gif",
        "https://media1.tenor.com/m/CG8uhh9CoJcAAAAC/shikimori-shikimoris-not-just-cute.gif",
        "https://media1.tenor.com/m/ETvEeDnbX7AAAAAC/my-dress-up-darling-anime-laugh.gif",
        "https://media1.tenor.com/m/EqrI4CB-grYAAAAC/anime-happy.gif",
        "https://media1.tenor.com/m/fXIixrnaemQAAAAC/laughing-laugh.gif"
    ],
    "happy": [
        "https://media1.tenor.com/m/89QSIUPhqBkAAAAC/anime-girl-happy.gif",
        "https://media1.tenor.com/m/EbNeN8Sf8QwAAAAC/umaru-hyper.gif",
        "https://media1.tenor.com/m/MM3La2Dx0c4AAAAC/onimai-cute-anime-girl-smile-smiling.gif",
        "https://media1.tenor.com/m/dNcXa6SrTrQAAAAC/himouto-umaru-chan-anime-smile.gif"
    ],
    "angry": [
        "https://media1.tenor.com/m/cYRAeQqpaUMAAAAC/anime-angry-slow-loop.gif",
        "https://media1.tenor.com/m/htdgCMyK5vMAAAAC/demon-slayer-kimetsu-no-yaiba.gif",
        "https://media1.tenor.com/m/PuKJo_l7J0YAAAAC/anime-angry.gif",
        "https://media1.tenor.com/m/hkoyf1VeaZ4AAAAC/anime-angry.gif",
        "https://media1.tenor.com/m/7nii-P6-h_UAAAAC/naruto-anime.gif",
        "https://media1.tenor.com/m/dDOpMoWUe1YAAAAC/nami-angry.gif",
        "https://media1.tenor.com/m/oUQBAn5ZZhQAAAAC/one-piece-anime.gif"
    ],
    "hmph": [
        "https://media1.tenor.com/m/3kvIVPYgTE8AAAAC/hmph-hmph-anime.gif",
        "https://media1.tenor.com/m/BLDYU-lBIsUAAAAC/anime-blushing.gif",
        "https://media1.tenor.com/m/UO-rToKtvIgAAAAC/pout-anime-pout.gif",
        "https://media1.tenor.com/m/ob2MggREvn0AAAAC/angry-hmph.gif",
        "https://media1.tenor.com/m/w2o1wq3145gAAAAC/ash-hmph.gif",
        "https://media1.tenor.com/m/fk67OlKF0GIAAAAC/anime-kawaii.gif"
    ],
    "salute": [
        "https://media1.tenor.com/m/dGI7oniuoIYAAAAC/one-piece-tashigi.gif",
        "https://media1.tenor.com/m/VjSzAK7nMcMAAAAC/86-anime-shin.gif",
        "https://media1.tenor.com/m/sfxSGwu6amkAAAAC/anya-forger-anya-spy-x-family-anime.gif",
        "https://media1.tenor.com/m/DCAEfX58OUUAAAAC/yes-sir.gif",
        "https://media1.tenor.com/m/o8NfjNUgeqcAAAAC/86-anime-shin.gif",
        "https://media1.tenor.com/m/DrWaCsbr95wAAAAC/anime-fuuko-ibuki.gif",
        "https://media1.tenor.com/m/tZ_67Q1lP80AAAAC/okay-salute.gif"
    ],
    #group GIFs
    "grouphug": [
        "https://media1.tenor.com/m/yXCeggloBOcAAAAC/k-on-op.gif",
        "https://media1.tenor.com/m/6Rm6NkFCBzQAAAAC/qu4rtz-love-live.gif",
        "https://media1.tenor.com/m/3KqBLsqVFhwAAAAC/animes-anime.gif",
        "https://media1.tenor.com/m/xBGS5okQp94AAAAC/d4dj-first-mix-anime.gif",
        "https://media1.tenor.com/m/TULvK6iT9O4AAAAC/anime-group-hug.gif",
        "https://media1.tenor.com/m/HBmX6ZzfcKYAAAAC/friends-tv-group-hug.gif",
        "https://media1.tenor.com/m/06yoEa6fxNAAAAAC/love-live-nijigasaki.gif",
        "https://media1.tenor.com/m/Pkw8lloUU38AAAAC/kitsune-upload-anime.gif"
    ],
    "groupdance":[

    ]
}