questions = {
    "Any Category": [
        {"question": "What is the capital of Australia?", "correct_answer": "Canberra", "incorrect_answers": ["Sydney", "Melbourne", "Brisbane"]},
        {"question": "Which country has the most population?", "correct_answer": "China", "incorrect_answers": ["India", "USA", "Brazil"]},
        {"question": "Which planet is known as the Red Planet?", "correct_answer": "Mars", "incorrect_answers": ["Venus", "Jupiter", "Saturn"]},
        {"question": "What is the largest mammal?", "correct_answer": "Blue Whale", "incorrect_answers": ["Elephant", "Giraffe", "Shark"]},
        {"question": "Which is the largest ocean on Earth?", "correct_answer": "Pacific Ocean", "incorrect_answers": ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"]},
        {"question": "What is the chemical symbol for water?", "correct_answer": "H2O", "incorrect_answers": ["O2", "CO2", "H2"]},
        {"question": "Which country is famous for the Eiffel Tower?", "correct_answer": "France", "incorrect_answers": ["Italy", "Germany", "Spain"]},
        {"question": "What is the national animal of India?", "correct_answer": "Lion", "incorrect_answers": ["Elephant", "Tiger", "Peacock"]},
        {"question": "Who developed the theory of relativity?", "correct_answer": "Albert Einstein", "incorrect_answers": ["Isaac Newton", "Nikola Tesla", "Galileo Galilei"]},
        {"question": "In which year did the Titanic sink?", "correct_answer": "1912", "incorrect_answers": ["1900", "1920", "1930"]},
        {"question": "What is the largest country in the world?", "correct_answer": "Russia", "incorrect_answers": ["Canada", "USA", "China"]},
        {"question": "Who was the first person to walk on the moon?", "correct_answer": "Neil Armstrong", "incorrect_answers": ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins"]},
        {"question": "Which animal is known for its black and white stripes?", "correct_answer": "Zebra", "incorrect_answers": ["Tiger", "Giraffe", "Cheetah"]},
        {"question": "Which is the longest river in the world?", "correct_answer": "Nile", "incorrect_answers": ["Amazon", "Yangtze", "Mississippi"]},
        {"question": "What does DNA stand for?", "correct_answer": "Deoxyribonucleic Acid", "incorrect_answers": ["Deoxyribonitric Acid", "Dioxyribonucleic Acid", "Deoxyribonucleic Atom"]},
        {"question": "What is the hardest natural substance on Earth?", "correct_answer": "Diamond", "incorrect_answers": ["Gold", "Iron", "Platinum"]},
        {"question": "What is the smallest planet in our solar system?", "correct_answer": "Mercury", "incorrect_answers": ["Mars", "Venus", "Pluto"]},
        {"question": "Which city is known as the Big Apple?", "correct_answer": "New York City", "incorrect_answers": ["Los Angeles", "Chicago", "Miami"]},
        {"question": "Which chemical element has the symbol O?", "correct_answer": "Oxygen", "incorrect_answers": ["Osmium", "Ozone", "Oxygenium"]},
        {"question": "Which element does 'O' represent in the periodic table?", "correct_answer": "Oxygen", "incorrect_answers": ["Osmium", "Ozone", "Oxygenium"]},
        {"question": "Who painted the Mona Lisa?", "correct_answer": "Leonardo da Vinci", "incorrect_answers": ["Pablo Picasso", "Vincent van Gogh", "Claude Monet"]},
        {"question": "What is the tallest mountain on Earth?", "correct_answer": "Mount Everest", "incorrect_answers": ["K2", "Kangchenjunga", "Makalu"]},
        {"question": "Which is the largest desert in the world?", "correct_answer": "Sahara Desert", "incorrect_answers": ["Gobi Desert", "Kalahari Desert", "Arabian Desert"]},
        {"question": "Which planet is closest to the sun?", "correct_answer": "Mercury", "incorrect_answers": ["Venus", "Earth", "Mars"]},
        {"question": "Which country is known for the Great Wall?", "correct_answer": "China", "incorrect_answers": ["India", "Japan", "Egypt"]},
        {"question": "Which animal is known for its ability to regenerate limbs?", "correct_answer": "Axolotl", "incorrect_answers": ["Lizard", "Starfish", "Gecko"]},
        {"question": "What is the capital of Japan?", "correct_answer": "Tokyo", "incorrect_answers": ["Osaka", "Kyoto", "Hiroshima"]},
        {"question": "Which ocean is the largest?", "correct_answer": "Pacific Ocean", "incorrect_answers": ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"]},
        {"question": "Which bird is known for its distinctive red breast?", "correct_answer": "Robin", "incorrect_answers": ["Blue Jay", "Sparrow", "Eagle"]},
        {"question": "Which instrument is known as the king of instruments?", "correct_answer": "Pipe Organ", "incorrect_answers": ["Piano", "Violin", "Trumpet"]},
        {"question": "Who discovered electricity?", "correct_answer": "Benjamin Franklin", "incorrect_answers": ["Thomas Edison", "Nikola Tesla", "Albert Einstein"]},
        {"question": "Which is the most widely spoken language in the world?", "correct_answer": "Mandarin Chinese", "incorrect_answers": ["English", "Spanish", "Hindi"]},
        {"question": "What is the primary ingredient in guacamole?", "correct_answer": "Avocado", "incorrect_answers": ["Tomato", "Cucumber", "Onion"]},
        {"question": "Which country is home to the ancient ruins of Machu Picchu?", "correct_answer": "Peru", "incorrect_answers": ["Mexico", "Brazil", "Chile"]},
        {"question": "What is the chemical symbol for gold?", "correct_answer": "Au", "incorrect_answers": ["Ag", "Fe", "Pb"]},
        {"question": "What is the largest island in the world?", "correct_answer": "Greenland", "incorrect_answers": ["Australia", "New Guinea", "Borneo"]},
        {"question": "Which body of water separates Saudi Arabia and Egypt?", "correct_answer": "Red Sea", "incorrect_answers": ["Arabian Sea", "Mediterranean Sea", "Persian Gulf"]},
        {"question": "Who invented the telephone?", "correct_answer": "Alexander Graham Bell", "incorrect_answers": ["Thomas Edison", "Nikola Tesla", "Michael Faraday"]},
        {"question": "Which country is known for the Eiffel Tower?", "correct_answer": "France", "incorrect_answers": ["Italy", "Germany", "Spain"]},
        {"question": "Who developed the theory of relativity?", "correct_answer": "Albert Einstein", "incorrect_answers": ["Isaac Newton", "Nikola Tesla", "Galileo Galilei"]},
    ],

    "General Knowledge": [
        {"question": "Which country has the most population?", "correct_answer": "China", "incorrect_answers": ["India", "USA", "Brazil"]},
        {"question": "What is the capital of Canada?", "correct_answer": "Ottawa", "incorrect_answers": ["Toronto", "Vancouver", "Montreal"]},
        {"question": "Who wrote *Romeo and Juliet*?", "correct_answer": "William Shakespeare", "incorrect_answers": ["Charles Dickens", "Jane Austen", "Mark Twain"]},
        {"question": "Which planet is known as the Red Planet?", "correct_answer": "Mars", "incorrect_answers": ["Venus", "Jupiter", "Saturn"]},
        {"question": "Who invented the light bulb?", "correct_answer": "Thomas Edison", "incorrect_answers": ["Nikola Tesla", "Benjamin Franklin", "Alexander Graham Bell"]},
        {"question": "Who painted the Mona Lisa?", "correct_answer": "Leonardo da Vinci", "incorrect_answers": ["Pablo Picasso", "Vincent van Gogh", "Claude Monet"]},
        {"question": "Which is the longest river in the world?", "correct_answer": "Nile", "incorrect_answers": ["Amazon", "Yangtze", "Mississippi"]},
        {"question": "Which is the largest country by area?", "correct_answer": "Russia", "incorrect_answers": ["Canada", "China", "United States"]},
        {"question": "Which is the largest desert in the world?", "correct_answer": "Sahara Desert", "incorrect_answers": ["Gobi Desert", "Kalahari Desert", "Arabian Desert"]},
        {"question": "What is the currency of Japan?", "correct_answer": "Yen", "incorrect_answers": ["Won", "Yuan", "Ringgit"]},
        {"question": "Who discovered gravity?", "correct_answer": "Isaac Newton", "incorrect_answers": ["Albert Einstein", "Galileo Galilei", "Nicolas Copernicus"]},
        {"question": "What is the capital of France?", "correct_answer": "Paris", "incorrect_answers": ["Rome", "London", "Madrid"]},
        {"question": "Which country is famous for the Eiffel Tower?", "correct_answer": "France", "incorrect_answers": ["Italy", "Germany", "Spain"]},
        {"question": "Who was the first woman to win a Nobel Prize?", "correct_answer": "Marie Curie", "incorrect_answers": ["Rosalind Franklin", "Ada Lovelace", "Florence Nightingale"]},
        {"question": "Which is the largest planet in our solar system?", "correct_answer": "Jupiter", "incorrect_answers": ["Saturn", "Neptune", "Earth"]},
        {"question": "Which famous landmark is located in Egypt?", "correct_answer": "Pyramids of Giza", "incorrect_answers": ["Great Wall of China", "Machu Picchu", "Colosseum"]},
        {"question": "Which is the largest mammal?", "correct_answer": "Blue Whale", "incorrect_answers": ["Elephant", "Giraffe", "Shark"]},
        {"question": "Which continent is known as the 'Dark Continent'?", "correct_answer": "Africa", "incorrect_answers": ["Asia", "Australia", "Antarctica"]},
        {"question": "Which country is known for the Great Wall?", "correct_answer": "China", "incorrect_answers": ["India", "Japan", "Egypt"]},
        {"question": "What is the capital of India?", "correct_answer": "New Delhi", "incorrect_answers": ["Mumbai", "Kolkata", "Bangalore"]},
        {"question": "Who developed the first successful airplane?", "correct_answer": "Wright brothers", "incorrect_answers": ["Charles Lindbergh", "Amelia Earhart", "Howard Hughes"]},
        {"question": "Who was the first person to step on the moon?", "correct_answer": "Neil Armstrong", "incorrect_answers": ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins"]},
    ],

    "Entertainment: Film": [
        {"question": "Who directed the movie *Inception*?", "correct_answer": "Christopher Nolan", "incorrect_answers": ["Steven Spielberg", "Martin Scorsese", "Quentin Tarantino"]},
        {"question": "Which movie won the Academy Award for Best Picture in 2019?", "correct_answer": "Parasite", "incorrect_answers": ["Green Book", "Bohemian Rhapsody", "1917"]},
        {"question": "Who starred as the titular character in *Pirates of the Caribbean*?", "correct_answer": "Johnny Depp", "incorrect_answers": ["Brad Pitt", "Leonardo DiCaprio", "Tom Cruise"]},
        {"question": "What is the name of the fictional African country in *Black Panther*?", "correct_answer": "Wakanda", "incorrect_answers": ["Zamunda", "Genovia", "Elbonia"]},
        {"question": "Which movie features the quote 'You can't handle the truth!'?", "correct_answer": "*A Few Good Men*", "incorrect_answers": ["*The Godfather*", "*Gladiator*", "*The Shawshank Redemption*"]},
        {"question": "Who played the Joker in *The Dark Knight*?", "correct_answer": "Heath Ledger", "incorrect_answers": ["Jared Leto", "Jack Nicholson", "Joaquin Phoenix"]},
        {"question": "Which actor starred as Forrest Gump?", "correct_answer": "Tom Hanks", "incorrect_answers": ["Matt Damon", "Brad Pitt", "Johnny Depp"]},
        {"question": "What year was *The Matrix* released?", "correct_answer": "1999", "incorrect_answers": ["1997", "2000", "2002"]},
        {"question": "Which film features a character named Neo?", "correct_answer": "*The Matrix*", "incorrect_answers": ["*Inception*", "*Avatar*", "*Blade Runner*"]},
        {"question": "Which actor played Tony Stark/Iron Man in the Marvel Cinematic Universe?", "correct_answer": "Robert Downey Jr.", "incorrect_answers": ["Chris Hemsworth", "Chris Evans", "Mark Ruffalo"]},
        {"question": "Who directed *Jurassic Park*?", "correct_answer": "Steven Spielberg", "incorrect_answers": ["George Lucas", "James Cameron", "Peter Jackson"]},
    ],

    "Entertainment: Music": [
        {"question": "Who is known as the 'King of Pop'?", "correct_answer": "Michael Jackson", "incorrect_answers": ["Elvis Presley", "Prince", "Justin Timberlake"]},
        {"question": "Which band was Freddie Mercury the lead vocalist for?", "correct_answer": "Queen", "incorrect_answers": ["The Beatles", "The Rolling Stones", "AC/DC"]},
        {"question": "What year did The Beatles break up?", "correct_answer": "1970", "incorrect_answers": ["1965", "1975", "1980"]},
        {"question": "Which famous singer is known for the hit song *Rolling in the Deep*?", "correct_answer": "Adele", "incorrect_answers": ["Beyoncé", "Rihanna", "Shakira"]},
        {"question": "Which of these is a popular song by Ed Sheeran?", "correct_answer": "*Shape of You*", "incorrect_answers": ["*Blinding Lights*", "*Levitating*", "*Bad Habits*"]},
        {"question": "What was Elvis Presley’s first number one hit song?", "correct_answer": "*Heartbreak Hotel*", "incorrect_answers": ["*Jailhouse Rock*", "*Can't Help Falling in Love*", "*Hound Dog*"]},
        {"question": "Which music genre did Nirvana help popularize?", "correct_answer": "Grunge", "incorrect_answers": ["Punk", "Metal", "Pop"]},
        {"question": "Who is known for the hit song *Purple Rain*?", "correct_answer": "Prince", "incorrect_answers": ["Michael Jackson", "David Bowie", "Stevie Wonder"]},
        {"question": "What genre is Taylor Swift primarily associated with?", "correct_answer": "Country-Pop", "incorrect_answers": ["Pop", "Rock", "Rap"]},
        {"question": "What band released the album *Dark Side of the Moon*?", "correct_answer": "Pink Floyd", "incorrect_answers": ["The Rolling Stones", "Led Zeppelin", "The Beatles"]},
        {"question": "What is the name of Beyoncé's debut album?", "correct_answer": "Dangerously in Love", "incorrect_answers": ["B'Day", "I Am... Sasha Fierce", "Lemonade"]},
        {"question": "Which of these artists is known for the song *Uptown Funk*?", "correct_answer": "Mark Ronson ft. Bruno Mars", "incorrect_answers": ["Pharrell Williams", "Justin Timberlake", "Sam Smith"]},
        {"question": "Who was the first woman inducted into the Rock and Roll Hall of Fame?", "correct_answer": "Aretha Franklin", "incorrect_answers": ["Janis Joplin", "Stevie Nicks", "Tina Turner"]},
        {"question": "Which band sang *Bohemian Rhapsody*?", "correct_answer": "Queen", "incorrect_answers": ["The Who", "Led Zeppelin", "The Beatles"]},
        {"question": "Which famous singer had a popular song titled *Havana*?", "correct_answer": "Camila Cabello", "incorrect_answers": ["Shakira", "Ariana Grande", "Katy Perry"]},
        {"question": "Who is known as the 'Material Girl'?", "correct_answer": "Madonna", "incorrect_answers": ["Cyndi Lauper", "Cher", "Lady Gaga"]},
        {"question": "What is the name of Justin Bieber’s debut album?", "correct_answer": "My World 2.0", "incorrect_answers": ["Purpose", "Believe", "Changes"]},
        {"question": "What genre is Billie Eilish primarily known for?", "correct_answer": "Alternative Pop", "incorrect_answers": ["Pop", "Rock", "Electronic"]},
        {"question": "Which artist is famous for the song *Blinding Lights*?", "correct_answer": "The Weeknd", "incorrect_answers": ["Drake", "Post Malone", "Kendrick Lamar"]},
        {"question": "Who sang *I Will Always Love You*?", "correct_answer": "Whitney Houston", "incorrect_answers": ["Celine Dion", "Mariah Carey", "Barbra Streisand"]},
        {"question": "What was Michael Jackson's last studio album?", "correct_answer": "Invincible", "incorrect_answers": ["Bad", "Thriller", "Dangerous"]},
        {"question": "Which artist's real name is Stefani Joanne Angelina Germanotta?", "correct_answer": "Lady Gaga", "incorrect_answers": ["Katy Perry", "Rihanna", "Ariana Grande"]},
    ],

    "Science: Computers": [
        {"question": "Who is known as the father of the computer?", "correct_answer": "Charles Babbage", "incorrect_answers": ["Alan Turing", "John von Neumann", "Bill Gates"]},
        {"question": "What does 'HTML' stand for?", "correct_answer": "HyperText Markup Language", "incorrect_answers": ["HyperText Machine Language", "HighText Markup Language", "HyperTool Markup Language"]},
        {"question": "What is the main function of the CPU in a computer?", "correct_answer": "To execute instructions", "incorrect_answers": ["To store data", "To display output", "To power the system"]},
        {"question": "What does 'RAM' stand for?", "correct_answer": "Random Access Memory", "incorrect_answers": ["Read Access Memory", "Rapid Access Memory", "Random Allocation Memory"]},
        {"question": "Which programming language is primarily used for web development?", "correct_answer": "JavaScript", "incorrect_answers": ["Python", "Java", "C++"]},
        {"question": "Which company developed the Windows operating system?", "correct_answer": "Microsoft", "incorrect_answers": ["Apple", "IBM", "Google"]},
        {"question": "Who co-founded Apple Inc. along with Steve Jobs?", "correct_answer": "Steve Wozniak", "incorrect_answers": ["Bill Gates", "Mark Zuckerberg", "Larry Page"]},
        {"question": "What does 'URL' stand for?", "correct_answer": "Uniform Resource Locator", "incorrect_answers": ["Uniform Resource Link", "Universal Resource Locator", "Universal Resource Link"]},
        {"question": "What does the abbreviation 'HTTP' stand for?", "correct_answer": "HyperText Transfer Protocol", "incorrect_answers": ["HyperText Transfer Process", "Hyper Terminal Transfer Protocol", "HyperText Type Protocol"]},
        {"question": "Which programming language is known as the mother of all languages?", "correct_answer": "C", "incorrect_answers": ["Java", "Python", "Fortran"]},
        {"question": "What was the first computer virus?", "correct_answer": "Creeper", "incorrect_answers": ["ILOVEYOU", "MyDoom", "Sasser"]},
        {"question": "Who invented the first computer mouse?", "correct_answer": "Douglas Engelbart", "incorrect_answers": ["Bill Gates", "Steve Jobs", "Alan Turing"]},
        {"question": "What is the purpose of an operating system?", "correct_answer": "To manage hardware and software resources", "incorrect_answers": ["To provide internet access", "To run applications", "To manage network connections"]},
        {"question": "Which company developed the first personal computer?", "correct_answer": "IBM", "incorrect_answers": ["Apple", "Microsoft", "Compaq"]},
        {"question": "Which technology is used to make web pages interactive?", "correct_answer": "JavaScript", "incorrect_answers": ["HTML", "CSS", "PHP"]},
        {"question": "Which company created the programming language Java?", "correct_answer": "Sun Microsystems", "incorrect_answers": ["Microsoft", "IBM", "Oracle"]},
        {"question": "What does 'IP' stand for in networking?", "correct_answer": "Internet Protocol", "incorrect_answers": ["Internal Protocol", "Interconnected Protocol", "Internet Point"]},
        {"question": "Which term is used for a file system's ability to support multiple simultaneous operations?", "correct_answer": "Concurrency", "incorrect_answers": ["Multitasking", "Parallelism", "Execution"]},
        {"question": "Which language is primarily used to develop Android applications?", "correct_answer": "Java", "incorrect_answers": ["Swift", "C#", "Python"]},
        {"question": "What is the main function of a compiler?", "correct_answer": "To convert source code into machine code", "incorrect_answers": ["To run the program", "To debug the code", "To provide an interface"]},
        {"question": "What is the purpose of a router in a network?", "correct_answer": "To route data packets between networks", "incorrect_answers": ["To connect devices to the internet", "To protect networks from threats", "To connect local devices"]},
    ],

    "Science: Gadgets": [
        {"question": "Which company developed the first iPhone?", "correct_answer": "Apple", "incorrect_answers": ["Samsung", "Nokia", "Sony"]},
        {"question": "What is the main function of a smartphone's accelerometer?", "correct_answer": "To detect orientation and movement", "incorrect_answers": ["To measure battery life", "To monitor temperature", "To track network usage"]},
        {"question": "Which company created the first smartwatch?", "correct_answer": "Pebble", "incorrect_answers": ["Samsung", "Apple", "Garmin"]},
        {"question": "What does 'GPS' stand for?", "correct_answer": "Global Positioning System", "incorrect_answers": ["Global Processing System", "General Positioning Service", "Geographical Positioning System"]},
        {"question": "What is the primary purpose of a drone?", "correct_answer": "To provide aerial footage", "incorrect_answers": ["To collect weather data", "To deliver packages", "To map geographical locations"]},
        {"question": "Which company developed the first tablet computer?", "correct_answer": "Apple", "incorrect_answers": ["Microsoft", "Samsung", "Lenovo"]},
        {"question": "Which gadget is used for virtual reality experiences?", "correct_answer": "VR Headset", "incorrect_answers": ["Smartphone", "Smartwatch", "Fitbit"]},
        {"question": "What does 'Bluetooth' technology primarily allow?", "correct_answer": "Wireless communication between devices", "incorrect_answers": ["High-speed internet", "Data storage", "Long-range communication"]},
        {"question": "Which company developed the first successful digital camera?", "correct_answer": "Kodak", "incorrect_answers": ["Canon", "Sony", "Nikon"]},
        {"question": "Which device is used to track steps and fitness activities?", "correct_answer": "Fitness tracker", "incorrect_answers": ["Smartphone", "Smartwatch", "Tablet"]},
        {"question": "What is the function of a smart thermostat?", "correct_answer": "To control home temperature remotely", "incorrect_answers": ["To monitor home security", "To manage appliances", "To control home lighting"]},
        {"question": "Which company made the first commercially successful smartwatch?", "correct_answer": "Apple", "incorrect_answers": ["Samsung", "Garmin", "Pebble"]},
        {"question": "What is the main function of a drone's gimbal?", "correct_answer": "To stabilize the camera", "incorrect_answers": ["To monitor altitude", "To track location", "To record sound"]},
        {"question": "Which device allows hands-free voice communication and control?", "correct_answer": "Smart speaker", "incorrect_answers": ["Smartphone", "Laptop", "Smartwatch"]},
        {"question": "What is a major feature of augmented reality (AR)?", "correct_answer": "Overlaying digital elements on the real world", "incorrect_answers": ["Tracking physical movements", "Immersive 3D gaming", "Virtual world simulation"]},
        {"question": "Which company invented the first commercially successful tablet computer?", "correct_answer": "Apple", "incorrect_answers": ["Microsoft", "Samsung", "Sony"]},
        {"question": "What is the main function of a fitness band?", "correct_answer": "To track physical activities", "incorrect_answers": ["To play music", "To make calls", "To control smart devices"]},
        {"question": "What is a major use of an e-reader?", "correct_answer": "Reading digital books", "incorrect_answers": ["Making calls", "Watching videos", "Taking photos"]},
    ],

    "Science: Nature": [
        {"question": "What is the largest living organism on Earth?", "correct_answer": "Honey fungus", "incorrect_answers": ["Blue whale", "Giant sequoia", "African elephant"]},
        {"question": "What is the process by which plants make food using sunlight?", "correct_answer": "Photosynthesis", "incorrect_answers": ["Respiration", "Fermentation", "Metabolism"]},
        {"question": "Which element is most abundant in the Earth's crust?", "correct_answer": "Oxygen", "incorrect_answers": ["Silicon", "Iron", "Aluminum"]},
        {"question": "Which animal is known for its ability to regenerate limbs?", "correct_answer": "Axolotl", "incorrect_answers": ["Starfish", "Lizard", "Gecko"]},
        {"question": "What is the largest type of bear?", "correct_answer": "Kodiak bear", "incorrect_answers": ["Polar bear", "Grizzly bear", "Black bear"]},
        {"question": "What is the primary function of roots in plants?", "correct_answer": "To absorb water and nutrients", "incorrect_answers": ["To produce seeds", "To create food", "To attract pollinators"]},
        {"question": "Which bird is known for its colorful feathers and ability to mimic sounds?", "correct_answer": "Parrot", "incorrect_answers": ["Crow", "Eagle", "Pigeon"]},
        {"question": "Which is the tallest tree species in the world?", "correct_answer": "Coast Redwood", "incorrect_answers": ["Giant Sequoia", "Douglas Fir", "Blue Spruce"]},
        {"question": "Which marine animal is known for its ability to change colors?", "correct_answer": "Octopus", "incorrect_answers": ["Shark", "Dolphin", "Whale"]},
        {"question": "What is the primary cause of ocean acidification?", "correct_answer": "Increased carbon dioxide levels", "incorrect_answers": ["Oil spills", "Overfishing", "Plastic pollution"]},
        {"question": "Which mammal is known for laying eggs?", "correct_answer": "Platypus", "incorrect_answers": ["Kangaroo", "Opossum", "Koala"]},
        {"question": "What is the fastest land animal?", "correct_answer": "Cheetah", "incorrect_answers": ["Lion", "Gazelle", "Elephant"]},
        {"question": "Which is the most venomous snake in the world?", "correct_answer": "Inland Taipan", "incorrect_answers": ["King cobra", "Black mamba", "Gaboon viper"]},
        {"question": "What is the chemical element with the symbol H?", "correct_answer": "Hydrogen", "incorrect_answers": ["Helium", "Hassium", "Holmium"]},
        {"question": "Which animal has the longest lifespan?", "correct_answer": "Bowhead whale", "incorrect_answers": ["Tortoise", "Elephant", "Human"]},
        {"question": "Which plant is famous for its ability to eat insects?", "correct_answer": "Venus flytrap", "incorrect_answers": ["Cactus", "Oak tree", "Pineapple"]},
        {"question": "Which forest is the largest tropical rainforest in the world?", "correct_answer": "Amazon Rainforest", "incorrect_answers": ["Congo Rainforest", "Daintree Rainforest", "Borneo Rainforest"]},
        {"question": "What is the primary source of energy for the Earth's ecosystem?", "correct_answer": "The Sun", "incorrect_answers": ["The Moon", "Wind", "Water"]},
        {"question": "Which animal is known for its long migrations across the globe?", "correct_answer": "Monarch butterfly", "incorrect_answers": ["Humpback whale", "Arctic Tern", "Elephant"]},
        {"question": "What is the chemical symbol for gold?", "correct_answer": "Au", "incorrect_answers": ["Ag", "Pb", "Cu"]},
    ],

    "Sports": [
        {"question": "Which country won the 2018 FIFA World Cup?", "correct_answer": "France", "incorrect_answers": ["Brazil", "Germany", "Argentina"]},
        {"question": "Which sport is known as the 'king of sports'?", "correct_answer": "Soccer", "incorrect_answers": ["Basketball", "Cricket", "Rugby"]},
        {"question": "Which athlete holds the record for the most Olympic gold medals?", "correct_answer": "Michael Phelps", "incorrect_answers": ["Usain Bolt", "Larisa Latynina", "Simone Biles"]},
        {"question": "What sport is Serena Williams famous for?", "correct_answer": "Tennis", "incorrect_answers": ["Basketball", "Soccer", "Golf"]},
        {"question": "Which country hosted the 2020 Summer Olympics?", "correct_answer": "Japan", "incorrect_answers": ["China", "Brazil", "Russia"]},
        {"question": "In what sport would you perform a slam dunk?", "correct_answer": "Basketball", "incorrect_answers": ["Volleyball", "Football", "Baseball"]},
        {"question": "Which country has won the most Rugby World Cup titles?", "correct_answer": "New Zealand", "incorrect_answers": ["South Africa", "Australia", "England"]},
        {"question": "Who holds the record for most home runs in a single MLB season?", "correct_answer": "Barry Bonds", "incorrect_answers": ["Babe Ruth", "Hank Aaron", "Mark McGwire"]},
        {"question": "Which city is known as the birthplace of the Olympic Games?", "correct_answer": "Olympia", "incorrect_answers": ["Rome", "Paris", "Athens"]},
        {"question": "What sport is associated with Wimbledon?", "correct_answer": "Tennis", "incorrect_answers": ["Golf", "Cricket", "Badminton"]},
        {"question": "Who is considered the greatest football player of all time?", "correct_answer": "Pelé", "incorrect_answers": ["Lionel Messi", "Cristiano Ronaldo", "Diego Maradona"]},
        {"question": "Which sport involves a ball and is played on ice?", "correct_answer": "Ice hockey", "incorrect_answers": ["Curling", "Lacrosse", "Football"]},
        {"question": "Which country has won the most FIFA World Cup titles?", "correct_answer": "Brazil", "incorrect_answers": ["Germany", "Italy", "Argentina"]},
        {"question": "In what sport would you use a bat and ball to hit a pitched ball?", "correct_answer": "Baseball", "incorrect_answers": ["Golf", "Cricket", "Softball"]},
        {"question": "Which tennis player has the most Grand Slam singles titles?", "correct_answer": "Margaret Court", "incorrect_answers": ["Serena Williams", "Venus Williams", "Steffi Graf"]},
        {"question": "What is the maximum break in snooker?", "correct_answer": "147", "incorrect_answers": ["100", "200", "120"]},
        {"question": "Who is the most decorated Olympic athlete of all time?", "correct_answer": "Michael Phelps", "incorrect_answers": ["Usain Bolt", "Larisa Latynina", "Simone Biles"]},
        {"question": "In which sport would you participate in the *Tour de France*?", "correct_answer": "Cycling", "incorrect_answers": ["Football", "Tennis", "Basketball"]},
        {"question": "Who is known as the 'Fastest Man on Earth'?", "correct_answer": "Usain Bolt", "incorrect_answers": ["Tyson Gay", "Michael Johnson", "Carl Lewis"]},
        {"question": "What is the length of an NFL football field?", "correct_answer": "100 yards", "incorrect_answers": ["120 yards", "80 yards", "150 yards"]},
    ]
}
