emoji_dict = {
    "happy": "😊", "joy": "😊", "smile": "😄", "grin": "😄", "laugh": "😂", "lol": "😂",
    "love": "❤️", "heart": "❤️", "romance": "❤️", "affection": "❤️", "like": "👍", "thumbs up": "👍",
    "ok": "👌", "fine": "👌", "perfect": "👌", "cool": "😎", "awesome": "😎", "great": "😎",
    "fire": "🔥", "lit": "🔥", "hot": "🔥", "angry": "😠", "mad": "😠", "furious": "😠",
    "sad": "😢", "cry": "😭", "tears": "😭", "upset": "😢", "broken": "💔", "heartbreak": "💔",
    "dog": "🐶", "puppy": "🐶", "cat": "🐱", "kitten": "🐱", "star": "⭐", "shine": "⭐",
    "moon": "🌙", "night": "🌙", "sun": "☀️", "day": "☀️", "gift": "🎁", "present": "🎁",
    "party": "🥳", "celebrate": "🥳", "balloon": "🎈", "fun": "🎈", "clap": "👏", "applause": "👏",
    "strong": "💪", "power": "💪", "muscle": "💪", "book": "📚", "read": "📚", "study": "📚",
    "rocket": "🚀", "space": "🚀", "travel": "✈️", "fly": "✈️", "car": "🚗", "drive": "🚗",
    "bus": "🚌", "ride": "🚌", "bike": "🚴", "cycling": "🚴", "train": "🚆", "rail": "🚆",
    "camera": "📷", "photo": "📷", "picture": "📷", "music": "🎶", "song": "🎶", "melody": "🎶",
    "game": "🎮", "play": "🎮", "fun": "🎮", "coffee": "☕", "tea": "☕", "drink": "☕",
    "beer": "🍺", "alcohol": "🍺", "cheers": "🍺", "pizza": "🍕", "food": "🍕", "yum": "🍕",
    "burger": "🍔", "fries": "🍟", "snack": "🍟", "ice cream": "🍨", "dessert": "🍨", "sweet": "🍨",
    "apple": "🍎", "fruit": "🍎", "grape": "🍇", "banana": "🍌", "strawberry": "🍓", "watermelon": "🍉",
    "money": "💰", "rich": "💰", "cash": "💰", "coins": "🪙", "bank": "🏦", "credit": "💳",
    "phone": "📱", "call": "📱", "mobile": "📱", "text": "💬", "message": "💬", "chat": "💬",
    "computer": "💻", "laptop": "💻", "tech": "💻", "robot": "🤖", "ai": "🤖", "future": "🤖",
    "alien": "👽", "space": "👽", "ghost": "👻", "scary": "👻", "spooky": "👻", "halloween": "🎃",
    "pumpkin": "🎃", "fall": "🍂", "autumn": "🍂", "winter": "❄️", "snow": "❄️", "cold": "❄️",
    "hot": "🌞", "summer": "🌞", "beach": "🏖️", "ocean": "🌊", "wave": "🌊", "swim": "🏊",
    "football": "🏈", "soccer": "⚽", "basketball": "🏀", "tennis": "🎾", "golf": "⛳", "trophy": "🏆",
    "winner": "🏆", "champion": "🏆", "medal": "🥇", "gold": "🥇", "silver": "🥈", "bronze": "🥉",
    "travel": "🌍", "world": "🌍", "adventure": "🌍", "map": "🗺️", "explore": "🗺️", "vacation": "🏖️",
    "house": "🏠", "home": "🏠", "building": "🏢", "school": "🏫", "university": "🏫", "office": "🏢",
    "work": "💼", "job": "💼", "career": "💼", "boss": "👔", "meeting": "📅", "schedule": "📅",
    "pen": "🖊️", "write": "🖊️", "note": "📝", "document": "📄", "file": "📄", "paper": "📄",
    "doctor": "👩‍⚕️", "nurse": "👩‍⚕️", "hospital": "🏥", "health": "❤️", "medicine": "💊", "pill": "💊",
    "police": "👮", "law": "⚖️", "judge": "⚖️", "fire": "🔥", "rescue": "🚒", "safety": "🛡️",
    "teacher": "👩‍🏫", "student": "👨‍🎓", "learn": "📚", "study": "📚", "exam": "📝", "test": "📝",
    "artist": "🎨", "paint": "🎨", "draw": "✏️", "design": "🎨", "creative": "🎨", "color": "🎨",
    "hello": "👋", "hi": "👋", "greetings": "👋", "bye": "👋", "goodbye": "👋", "see you": "👋",
    "family": "👨‍👩‍👧‍👦", "parents": "👨‍👩‍👧‍👦", "friends": "👯", "bestie": "👯", "couple": "❤️", "love": "❤️",
    "wedding": "💒", "bride": "👰", "groom": "🤵", "ring": "💍", "marriage": "💍", "anniversary": "💍",
    "baby": "👶", "child": "👶", "kid": "👦", "boy": "👦", "girl": "👧", "teen": "🧒",
    "strong": "💪", "fit": "💪", "gym": "🏋️", "workout": "🏋️", "run": "🏃", "jog": "🏃",
    "dance": "💃", "party": "🥳", "music": "🎶", "concert": "🎤", "sing": "🎤", "microphone": "🎤",
    "light": "💡", "idea": "💡", "brain": "🧠", "think": "🤔", "smart": "🧠", "genius": "🧠",
    "time": "⏰", "clock": "⏰", "watch": "⌚", "alarm": "⏰", "calendar": "📆", "date": "📆",
    "weather": "⛅", "cloud": "☁️", "rain": "🌧️", "storm": "⛈️", "lightning": "⚡", "wind": "🌬️",
    "mountain": "⛰️", "hiking": "🥾", "adventure": "⛺", "camping": "⛺", "forest": "🌳", "tree": "🌳",
    "animal": "🐾", "pet": "🐾", "wild": "🦁", "zoo": "🦓", "jungle": "🦍", "farm": "🐄",
    "flower": "🌸", "rose": "🌹", "garden": "🌼", "plant": "🪴", "leaf": "🍃", "nature": "🌿",
    "gift": "🎁", "surprise": "🎁", "box": "📦", "package": "📦", "shopping": "🛒", "store": "🏪"
}
